[Feature] CON 81 - Enable text wrap passages
oat-sa/extension-tao-devtools pull request #185
Opened 2020-11-13 15:35 UTC by habemuscode

**Related to this issue**

https://oat-sa.atlassian.net/browse/CON-81

**Other related PRs**

- https://github.com/oat-sa/extension-tao-itemqti/pull/1580
- https://github.com/oat-sa/extension-tao-mediamanager/pull/240

**Story**

As the author, I want to be able to wrap my text around pictures, so that I can produce passages that look like real-life media content.

Currently, I am only able to anchor images AS a character. In order for the text to be able to flow around it, I will need to be able to anchor it TO a character and specify how text is supposed to wrap around it

Required wrap modes:

- Float off
- Float right
- Float left

**Acceptance Criteria**

- Anchoring an image as a character should still be possible
- Text wrapping should not be available when the image is anchored as a character
- Images maintain position within their paragraph when text is added before or after
- Responsive images are still supported if the image is anchored to a character
- Exported items will contain the relevant CSS to ensure the rendering will be correct in any environment
- Exporting and reimporting an item will maintain the anchoring and wrapping

2020-11-13 15:39 UTC, habemuscode commented
@bugalot I make a change in `manifest.php` because we don't `Updater` any longer more. Can you please validate?

2020-11-16 10:00 UTC, habemuscode commented
Comprobation that it's working, in TAO Icons tools in UI

![imagen](https://user-images.githubusercontent.com/34692207/99239110-e0b1fb80-27fa-11eb-81e3-26225b483985.png)

2020-11-16 10:25 UTC, bziondik requested changes
Please, check my comment

2020-11-16 10:25 UTC, bziondik commented on manifest.php
> -use oat\taoDevTools\scripts\update\Updater;
I think it should be in manifest

2020-11-16 11:35 UTC, habemuscode commented on manifest.php
> -use oat\taoDevTools\scripts\update\Updater;
ok I put again :D

2020-11-16 12:38 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-11-16 12:53 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-11-16 15:17 UTC, boajer approved these changes
Backend Part is awesome ! 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-16 15:41 UTC, merged